steps:
  - name: "gcr.io/cloud-builders/docker"
    id: "build"
    args:
      [
        "build",
        "-t",
        "gcr.io/rama-lab/github.com/ramadlana/00_fast_api_tutorial:fix",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    id: "push"
    args:
      ["push", "gcr.io/rama-lab/github.com/ramadlana/00_fast_api_tutorial:fix"]
  - name: "gcr.io/cloud-builders/gcloud"
    id: "deploy"
    waitFor: ["build"]
    args:
      [
        "run",
        "deploy",
        "fastapi",
        "--image=gcr.io/rama-lab/github.com/ramadlana/00_fast_api_tutorial:fix",
        "--region=asia-southeast2",
        "--project=rama-lab",
      ]

  - name: "gcr.io/cloud-builders/gcloud"
    id: "runservice"
    waitFor: ["build", "deploy"]
    args:
      [
        "run",
        "services",
        "update-traffic",
        "fastapi",
        "--to-latest",
        "--region=asia-southeast2",
      ]
